import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'

import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

export const metadata = {
  title: "Bouzi's Portfolio",
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
